steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/edit-broker-ci:$COMMIT_SHA', './edit-broker-ci' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/node-gcloud:$COMMIT_SHA', './node-gcloud' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'tag', 'gcr.io/$PROJECT_ID/node-gcloud:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/node-gcloud:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/node-gcloud-kube:$COMMIT_SHA', './node-gcloud-kube' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/node-gcloud-chrome:$COMMIT_SHA', './node-gcloud-chrome' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'tag', 'gcr.io/$PROJECT_ID/node-gcloud-chrome:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/node-gcloud-chrome:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/node-gcloud-kube-chrome:$COMMIT_SHA', './node-gcloud-kube-chrome' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/node-gcloud-ffmpeg:$COMMIT_SHA', './node-gcloud-ffmpeg' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/node-gcloud-ffmpeg-chrome:$COMMIT_SHA', './node-gcloud-ffmpeg-chrome' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'tag', 'gcr.io/$PROJECT_ID/node-gcloud-ffmpeg-chrome:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/node-gcloud-ffmpeg-chrome:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/node-gcloud-ffmpeg-chrome-java:$COMMIT_SHA', './node-gcloud-ffmpeg-chrome-java' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/gae-python:$COMMIT_SHA', './gae-python' ]
  waitFor: ['-']

images:
- 'gcr.io/$PROJECT_ID/edit-broker-ci:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/node-gcloud:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/node-gcloud:latest'
- 'gcr.io/$PROJECT_ID/node-gcloud-ffmpeg:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/node-gcloud-kube:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/node-gcloud-kube-chrome:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/node-gcloud-chrome:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/node-gcloud-ffmpeg-chrome:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/node-gcloud-ffmpeg-chrome-java:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/gae-python:$COMMIT_SHA'
tags:
- "ci"
timeout: 1200s
