steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/node-gcloud:$COMMIT_SHA', './node-gcloud' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'tag', 'gcr.io/$PROJECT_ID/node-gcloud:$COMMIT_SHA', 'gcr.io/$PROJECT_ID/node-gcloud:latest']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/node-gcloud-kube:$COMMIT_SHA', './node-gcloud-kube' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/node-chrome:$COMMIT_SHA', './node-gcloud-chrome' ]
images:
- 'gcr.io/$PROJECT_ID/node-gcloud:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/node-gcloud:latest'
- 'gcr.io/$PROJECT_ID/node-gcloud-kube:$COMMIT_SHA'
- 'gcr.io/$PROJECT_ID/node-chrome:$COMMIT_SHA'
tags:
- "ci"
